### ISSUE TITLE
increase DEFAULT_CONNECT_TIMEOUT

### ISSUE THREAD

**Issue by abhideodhar** [Seagate/kinetic-py#28]
While running kineticc client, occasionally I see this error:

Traceback (most recent call last):
  File "/usr/bin/kineticc", line 9, in <module>
    load_entry_point('kinetic==0.8.0-r0', 'console_scripts', 'kineticc')()
  File "/home/jmanish/kinetic-py-0.8.0/kinetic/cmd/__init__.py", line 295, in main
    errorcode = handle_loop(**vars(preparse_args))
  File "/home/jmanish/kinetic-py-0.8.0/kinetic/cmd/__init__.py", line 255, in handle_loop
    Cmd(**options).cmdloop()
  File "/home/jmanish/kinetic-py-0.8.0/kinetic/cmd/__init__.py", line 159, in __init__
    self.client.connect()
  File "/home/jmanish/kinetic-py-0.8.0/kinetic/asyncclient.py", line 48, in connect
    super(AsyncClient, self).connect()
  File "/home/jmanish/kinetic-py-0.8.0/kinetic/baseclient.py", line 127, in connect
    self._handshake()
  File "/home/jmanish/kinetic-py-0.8.0/kinetic/baseclient.py", line 141, in _handshake
    raise common.KineticClientException("Handshake timeout")
kinetic.common.KineticClientException: 'Handshake timeout'

After investigation, I found that there is a DEFAULT_CONNECT_TIMEOUT set to 0.1 in common.py.
The value of 0.1 seems too less as a timeout since the server could be busy.

After increasing this value to 5, I dont see the handshake timeout. So - I suggest that we change the DEFAULT_CONNECT_TIMEOUT to something more reasonable.

**Comment by abhideodhar** [comment]
@icorderi - any comment on this issue?

**Comment by icorderi** [comment]
@abhideodhar drives connect in about 2ms --or less-- which includes the handshake round. 
Establishing the socket connection is actually faster, 100ms to establish a socket connection within a cluster is a fairly long time.

The **Handshake timeout** most likely is due to trying to connect to a drive with a very old firmware that doesn't have handshake implemented (see [installation-guide]).

What firmware version do you have in your drives?

[installation-guide]: https://github.com/Seagate/kinetic-py#installing-from-source

**Comment by abhideodhar** [comment]
I am using kinetic protocol version 3.0.5 - but I do see Handshake timeouts when I run tests.

**Comment by abhideodhar** [comment]
I am using firmware with kinetic protocol version 3.0.5. Sometimes I see the handshake timeout during long running test.
